[package]
name = "make-vpn-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1"
pretty_env_logger = "0.5"
telepages = {git = "https://github.com/leofaraf/telepages.git"}